### ISSUE TITLE
 TypeError: this.child.open is not a function when trying newCollection

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#192]
Trying to following the instructions in https://docs.textile.io/threads/introduction/#developer-api

I seem to be able to work around the issue https://github.com/textileio/js-threads/issues/191 by just not using `db.open`. Instead, I just do,

```
    const threadID: ThreadID = ThreadID.fromRandom()
    const db = new Database(threadID)
    db.newCollection('dogs', schema)
```

But now the `newCollection` errors with, 

```
(node:28345) UnhandledPromiseRejectionWarning: TypeError: this.child.open is not a function
    at DomainDatastore.open (/Users/andrewhill/Textile/threads/demo/node_modules/datastore-core/src/keytransform.js:20:23)
    at Database.<anonymous> (/Users/andrewhill/Textile/threads/demo/node_modules/@textile/threads-database/src/db.ts:177:22)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/andrewhill/Textile/threads/demo/node_modules/@textile/threads-database/dist/db.js:14:58)
```

I'm using the same schema from the docs,

```json
const schema: JSONSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Person',
  type: 'object',
  properties: {
    _id: { type: 'string' },
    name: { type: 'string' },
    age: {
      type: 'number',
      minimum: 0,
      exclusiveMaximum: 100,
    },
  },
}
```

**Comment by carsonfarmer** [comment]
Yeh this is simply because the db isn't open yet for persistence. The fix here is better error handling and retuning a more useful error.

**Comment by carsonfarmer** [comment]
Just to be clear, the Database constructor does _not_ take ThreadID as an argument at the moment...
