### ISSUE TITLE
Client is dependent on globally defined Buffer Class

### ISSUE THREAD

**Issue by deefactorial** [textileio/js-threads#534]
**Describe the bug**
When calling function `client.newDb(undefined, 'threadName');` I get error:
```
stack: "ReferenceError: Buffer is not defined
    at Function.fromRandom (http://localhost:4200/vendor.js:121562:23)
    at Client.<anonymous> (http://localhost:4200/vendor.js:32112:102)
    at Generator.next (<anonymous>)
    at http://localhost:4200/vendor.js:31868:71
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:1057:33)
    at push.FPOR.__awaiter (http://localhost:4200/vendor.js:31864:12)
    at Client.newDB (http://localhost:4200/vendor.js:32111:16)
    at SwitchMapSubscriber.project (http://localhost:4200/main.js:503:227)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.js:64315:27)
    at SwitchMapSubscriber.next (http://localhost:4200/vendor.js:25496:18)"
```

**To Reproduce**
To reproduce the error remove the workaround found here:
https://github.com/deefactorial/thread-explorer/blob/master/src/app/store/threads/thread-data-collections.service.ts#L9-L10
and run the code as per the readme.md.

**Expected behavior**
I would expect that the Buffer class would be bundled with the client and not depend on a globally defined Buffer class.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser Chrome
 - Version @textile/hub@0.6.2

**Additional context**
This Client class is expecting a Buffer class to be defined in the global scope. When you are accessing the client class in an angular service it can't access the global scope so it can't find the Buffer class. the solution would be to explicitly bundle the Buffer class within the implementation of Client.

**Comment by deefactorial** [comment]
As a workaround for now I can explicitly pollute the global scope by doing:
```ts
import { Buffer } from 'buffer';
global.Buffer = Buffer;
```

**Comment by carsonfarmer** [comment]
Good call, I think we include buffer in js-hub, but not here yet. We should do the same everywhere. Ideally, we'd avoid using Buffer directly at all, but we're not quite there yet.
