### ISSUE TITLE
json: cannot unmarshal string into Go value of type jsonschema.Schema

### ISSUE THREAD

**Issue by deefactorial** [textileio/js-threads#535]
**Describe the bug**
When I try to run the method `client.newCollection(threadId, 'name', '{"type":"object"}')` I get error:
```
Error: json: cannot unmarshal string into Go value of type jsonschema.Schema
    at Object.onEnd (http://localhost:4200/vendor.js:50127:36)
    at http://localhost:4200/vendor.js:115667:24343
    at http://localhost:4200/vendor.js:115667:4892
    at Array.forEach (<anonymous>)
    at e.rawOnEnd (http://localhost:4200/vendor.js:115667:4855)
    at e.onTransportEnd (http://localhost:4200/vendor.js:115667:4562)
    at WebSocket.ws.onclose [as __zone_symbol__ON_PROPERTYclose] (http://localhost:4200/vendor.js:61448:25)
    at WebSocket.wrapFn (http://localhost:4200/polyfills.js:1315:43)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:496:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:98186:33)
```

**To Reproduce**

1. Goto https://github.com/deefactorial/thread-explorer
2. Follow Readme.md to install and build
3. Create New Thread
4. Create New Collection

**Expected behavior**
New Collection should be created.

**Screenshots**
<img width="1058" alt="Screen Shot 2020-09-13 at 1 41 01 PM" src="https://user-images.githubusercontent.com/4856696/93028165-e60a8400-f5c6-11ea-94e5-20272a95dd97.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Additional context**
https://github.com/deefactorial/thread-explorer/blob/master/src/app/store/collections/collection-data-collections.service.ts#L25-L27
https://github.com/deefactorial/thread-explorer/blob/master/src/app/components/collections/collections.component.ts#L34-L37

**Comment by deefactorial** [comment]
So I found out my issue was that I was trying to serialize JSON as a string.
